[runner]

magicEnabled = false


[theme]

primaryColor = "#84593D"
backgroundColor = "#E5D3B3"
secondaryBackgroundColor = "#B99976"
textColor = "#4C2B08"
linkColor = "#4B6F44"


[theme.sidebar]

primaryColor = "#525025"
backgroundColor = "#B99976"
secondaryBackgroundColor = "#E5D3B3"
textColor = "#4C2B08"
linkColor = "#4B6F44"
